#!/bin/bash

APELSIN_DIR="/home/s0001191/repos/apelsin_search"
BASH_HISTORY_PATH="/home/s0001191/.bash_history"
BASH_HISTORY_FAVORITES_PATH="$APELSIN_DIR/.bash_history_favorites"

alias apelsin='python3 $APELSIN_DIR/src/main.py --bash_history $BASH_HISTORY_PATH --bash_history_favorites $BASH_HISTORY_FAVORITES_PATH'

# bind apelsin to ctrl-e
bind '"\C-e": "\C-a apelsin \C-j"'
