#!/bin/bash

APELSIN_DIR="/home/s0001191/repos/apelsin_search"

apelsin()
{
    python $APELSIN_DIR/history_search.py

    if [ $? -eq 0 ]; then
        # Result from history search is written to file search_result
        command=$(cat $APELSIN_DIR/search_result)
        rm $APELSIN_DIR/search_result

        echo $command
        eval $command
    fi
}
